site_name: OSCRO云管理平台
nav:
  - README:
    - OSCRO项目: readme/产品介绍.md
    - 使用手册: readme/使用手册.md
theme:
  name: 'material'
  features:
  - navigation.tabs # 使用Tab来进行分类
  - navigation.top # 返回顶部的按钮 在上滑时出现
  - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
  - navigation.expand # 打开Tab时左侧目录全部展开
  - search.highlight # 搜索出的文章关键词加入高亮

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  #- plantuml

extra_css:
  - https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.css
  # - assets/one-dark.css

extra_javascript:
  - https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min.js
  - assets/material_nav_extend.js

extra:
  search:
    language: 'cn'
