# Project information
site_name: OSCRO应用平台
# Page tree
nav:
# - 首页:
# - 快速开始: ### 展示导航
#   - 入门概念:
#   - 快速安装:
#   - 快速入门:
  - 产品介绍: 
    - 产品概述: readme/concepts/产品介绍.md
    - 产品架构: readme/concepts/产品架构.md
    - 产品功能: readme/concepts/产品功能.md
  - 使用指南: ### 展示导航
    - 集群管理: readme/tutorials/集群管理.md
    - 平台管理: readme/tutorials/平台管理.md
    - 开发环境: readme/tutorials/开发环境.md
    - 应用中心: readme/tutorials/应用中心.md
    - 容器管理: readme/tutorials/容器管理.md
    - 应用变更管理: readme/tutorials/应用变更管理.md
  - Verison: ### 展示导航
    - 版本发布:
      - v1.0: readme/upgrade/v1.0.md
    #- 版本升级:
    #  - v1.0升级alpha-v1030: readme/upgrade/v1.0升级alpha-v1030.md
# Copyright        
copyright: Copyright © 2022 北京八分量信息科技有限公司
# Configuration
theme:
  name: 'material'   ## 参考https://squidfunk.github.io/mkdocs-material/
  language: zh # 默认语言
  features:
  - header.autohide # 标题栏自动隐藏
  - navigation.tabs # 导航标签
  - navigation.top # 返回顶部的按钮 在上滑时出现
  - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
  - navigation.expand # 打开Tab时左侧目录全部展开
  - search.highlight # 搜索出的文章关键词加入高亮
  favicon: readme/images/favicon.ico
  logo: readme/images/logo.png
  palette:          # 网站配色
    - scheme: default # 背景色
      primary: blue   # 主题色
      accent: purple  # 图块颜色 
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode     
  font:   # 字体配置
    text: Roboto
    code: Roboto Mono
# Extensions
markdown_extensions:
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  #- plantuml

extra_css:
  - https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.css
  # - assets/one-dark.css

extra_javascript:
  - https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min.js
  - assets/material_nav_extend.js
# Customization
extra:
  search:
    language: 'cn'
  # alternate:        # 英文切换
  #   - name: English
  #     link: /en/ 
  #     lang: en
# Plugins
plugins:
  - search:
      lang: en